# Generated by Django 2.0.5 on 2019-06-21 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_auto_20190621_2009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='teacher',
            new_name='teacher_id',
        ),
    ]
