# Generated by Django 2.0.5 on 2019-06-21 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_auto_20190621_2028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='teacher_id',
            new_name='teacher',
        ),
    ]
